{
  "openapi":"3.0.2",
  "info": {
    "title":"Proffy",
    "version":"1.0",
    "license": {
      "name": "MIT",
      "url": "https://github.com/DiegoVictor/proffy-api/blob/master/LICENSE"
    }
  },
  "servers": [
    {
      "url":"http://localhost:3333/v1"
    }
  ],
  "paths": {
    "/sessions": {
      "post": {
        "tags": ["sessions"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "title": "User",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              },
              "example": {
                "email": "johndoe@example.com",
                "password": "123456"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Authenticates user and return an access token.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "type": "object",
                      "title": "User",
                      "properties": {
                        "id": {
                          "type": "integer"
                        },
                        "email": {
                          "type": "string"
                        },
                        "name": {
                          "type": "string"
                        }
                      }
                    },
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "example": {
                  "user": {
                    "id": 1,
                    "email": "johndoe@example.com",
                    "name": "John"
                  },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjI5NTAwODYwLCJleHAiOjE2MzAxMDU2NjB9.M6caH28Vr-4K9FWwr278-TRWM6UDMKN1TYfwi33mCTk"
                }
              }
            }
          },
          "400": {
            "description": "User not existsor wrong password",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "examples": {
                  "User not exists": {
                    "description": "User not exists",
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "User not exists",
                      "code": 344,
                      "docs": "https://github.com/DiegoVictor/proffy-api#errors-reference"
                    }
                  },
                  "User and/or password not match": {
                    "description": "User and/or password not match",
                    "value": {
                      "statusCode": 400,
                      "error": "Bad Request",
                      "message": "User and/or password not match",
                      "code": 340,
                      "docs": "https://github.com/DiegoVictor/proffy-api#errors-reference"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema" : {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/User"
                  },
                  {
                    "title": "User",
                    "required": [
                      "name",
                      "surname",
                      "email",
                      "password",
                      "avatar",
                      "whatsapp",
                      "bio"
                    ],
                    "properties": {
                      "password": {
                        "type": "string"
                      }
                    }
                  }
                ]
              },
              "example": {
                "name": "John",
                "surname": "Doe",
                "email": "johndoe@example.com",
                "password": "123456",
                "avatar": "https://avatars2.githubusercontent.com/u/15165349?s=460&u=1013eaaceb8a54984f7f77bc21812ad68f6ef526&v=4",
                "whatsapp": "16558352882",
                "bio": "Quia vero neque vel quia ea. Expedita iusto et saepe nostrum id quam. Quibusdam deserunt nostrum ullam enim et dolorum. Est enim vero optio aut iure ut voluptatibus doloribus tenetur."
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Creates a new user"
          },
          "400": {
            "description": "Email already in use",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                },
                "example": {
                  "statusCode": 400,
                  "error": "Bad Request",
                  "message": "Email already in use",
                  "code": 240,
                  "docs": "https://github.com/DiegoVictor/proffy-api#errors-reference"
                }
              }
            }
          }
        }
      }
    },
  },
  "components": {
    "schemas": {
      "User": {
        "properties": {
          "name": {
            "type": "string"
          },
          "surname": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "avatar": {
            "type": "string"
          },
          "whatsapp": {
            "type": "string"
          },
          "bio": {
            "type": "string"
          }
        }
      },
      "Schedule": {
        "properties": {
          "weekday": {
            "type": "integer"
          },
          "from": {
            "type": "integer"
          },
          "to": {
            "type": "integer"
          },
          "class_id": {
            "type": "integer"
          }
        }
      },
      "Error": {
        "properties": {
          "statusCode": {
            "type": "integer"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "code": {
            "type": "integer"
          },
          "docs": {
            "type": "string"
          }
        }
      }
    },
  }
}
